apiVersion: apps/v1
kind: Deployment 
metadata:
  name: book-catalog 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: book-catalog 
  template: 
    metadata:
      labels:
        app: book-catalog 
    spec:
      containers: 
      - name: book-catalog
        image: s223828778.azurecr.io/book-catalog:1 
        imagePullPolicy: IfNotPresent 
        env: 
        - name: PORT
          value: "4001" 


--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: s223828778.azurecr.io/inventory-management:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4002"


--- #Divides the configuration file into two main sections
apiVersion: v1
kind: Service #Sets up a Kubernetes service that generates a DNS record and makes our microservice accessible to HTTP requests
metadata:
  name: book-catalog #Sets the name of the service spec: selector:
spec:
  selector:
    app: book-catalog #Links the deployment, pod, and service together
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
      

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4002